//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibraries
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Evdokimov_СityLibrariesEntities : DbContext
    {

        private static Evdokimov_СityLibrariesEntities _context;

        public static Evdokimov_СityLibrariesEntities GetContext()
        {
            if (_context == null)
                _context = new Evdokimov_СityLibrariesEntities();
            return _context;
        }

        public Evdokimov_СityLibrariesEntities()
            : base("name=Evdokimov_СityLibrariesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LIBRARIES> LIBRARIES { get; set; }
        public virtual DbSet<LITERATURE> LITERATURE { get; set; }
        public virtual DbSet<READERS> READERS { get; set; }
        public virtual DbSet<READING_ROOM> READING_ROOM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ISSUING_LITERATURE> ISSUING_LITERATURE { get; set; }
    }
}
