//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibraries
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUING_LITERATURE
    {
        public int ISSUING_LITERATURE_READER { get; set; }
        public int ISSUING_LITERATURE_LITERATURE { get; set; }
        public System.DateTime ISSUING_LITERATURE_DATE_OF_ISSUE { get; set; }
        public Nullable<System.DateTime> ISSUING_LITERATURE_ISSUANCE_DATE { get; set; }
        public string ISSUING_LITERATURE_TYPE_OF_ISSUANCE { get; set; }
        public string ISSUING_LITERATURE_DEPOSIT { get; set; }
    
        public virtual LITERATURE LITERATURE { get; set; }
        public virtual READERS READERS { get; set; }
    }
}
