//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibraries
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRARIES()
        {
            this.READING_ROOM = new HashSet<READING_ROOM>();
        }
    
        public int LIBRARY_ID { get; set; }
        public string LIBRARY_NAME { get; set; }
        public string LIBRARY_ADDRESS { get; set; }
        public string LIBRARY_CITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<READING_ROOM> READING_ROOM { get; set; }
    }
}
