//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibraries
{
    using System;
    using System.Collections.Generic;
    
    public partial class READING_ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public READING_ROOM()
        {
            this.LITERATURE = new HashSet<LITERATURE>();
        }
    
        public int READING_ROOM_ID { get; set; }
        public string READING_ROOM_NAME { get; set; }
        public int READING_ROOM_LIBRARY { get; set; }
        public int READING_ROOM_LITERATURE { get; set; }
        public int READING_ROOM_SEATS { get; set; }
        public string READING_ROOM_WORK_TIME { get; set; }
        public Nullable<int> READING_ROOM_FLOOR { get; set; }
        public Nullable<int> READING_ROOM_WORKERS { get; set; }
    
        public virtual LIBRARIES LIBRARIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LITERATURE> LITERATURE { get; set; }
    }
}
